package com.home_security.web_lead;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Community implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "inccyavehh")
	private java.lang.String inccyavehh;

	public Community() {
	}

	public java.lang.String getInccyavehh() {
		return this.inccyavehh;
	}

	public void setInccyavehh(java.lang.String inccyavehh) {
		this.inccyavehh = inccyavehh;
	}

	public Community(java.lang.String inccyavehh) {
		this.inccyavehh = inccyavehh;
	}

}