package com.home_security.web_lead;

import java.io.Serializable;

import org.kie.api.definition.type.*;


/**
 * This class was automatically generated by the data modeler tool.
 */

@Label("DNIS")
public class Dnis implements Serializable {

	private static final long serialVersionUID = -6529936226311854189L;
	@Label("Affiliate")
	private String affiliate;
	@Label("LOB")
	private String lob;
	@Label("Market Channel")
	private String marketChannel;
	@Label("Marketing Generic")
	private String marketingGeneric;
	@Label("Bypass Oneclick")
	private Boolean bypassOneclick;
	@Label("Bypass Email")
	private Boolean bypassEmail;
	@Label("Bypass Send Text")
	private Boolean bypassSendText;

	public Dnis() {
	}

	public String getAffiliate() {
		return this.affiliate;
	}

	public void setAffiliate(String affiliate) {
		this.affiliate = affiliate;
	}

	public String getLob() {
		return this.lob;
	}

	public void setLob(String lob) {
		this.lob = lob;
	}

	public String getMarketChannel() {
		return this.marketChannel;
	}

	public void setMarketChannel(String marketChannel) {
		this.marketChannel = marketChannel;
	}

	public String getMarketingGeneric() {
		return this.marketingGeneric;
	}

	public void setMarketingGeneric(String marketingGeneric) {
		this.marketingGeneric = marketingGeneric;
	}

	public Boolean getBypassOneclick() {
		return this.bypassOneclick;
	}

	public void setBypassOneclick(Boolean bypassOneclick) {
		this.bypassOneclick = bypassOneclick;
	}

	public Boolean getBypassEmail() {
		return this.bypassEmail;
	}

	public void setBypassEmail(Boolean bypassEmail) {
		this.bypassEmail = bypassEmail;
	}

	public Boolean getBypassSendText() {
		return this.bypassSendText;
	}

	public void setBypassSendText(Boolean bypassSendText) {
		this.bypassSendText = bypassSendText;
	}

	@Override
	public String toString() {
		return
	//	"{affiliate: "+((affiliate==null) ? : "null" : affiliate)+"\n"+
		"{bypassEmail: "+bypassEmail+"\n"+
		" bypassOneclick: "+bypassOneclick+"\n"+
		" bypassSendtext: "+bypassSendText+"\n"+
		" lob: "+lob+"\n"+
		" affiliate: "+affiliate+"\n"+
		" marketChannel: "+marketChannel+"\n"+
		" marketingGeneric: "+marketingGeneric+"\n"+
		"}\n";
	}

	public Dnis(String affiliate, String lob,
			String marketChannel, String marketingGeneric,
			Boolean bypassOneclick, Boolean bypassEmail,
			Boolean bypassSendText) {
		this.affiliate = affiliate;
		this.lob = lob;
		this.marketChannel = marketChannel;
		this.marketingGeneric = marketingGeneric;
		this.bypassOneclick = bypassOneclick;
		this.bypassEmail = bypassEmail;
		this.bypassSendText = bypassSendText;
	}

}