package com.home_security.web_lead;

import java.io.Serializable;

import org.kie.api.definition.type.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Label("Response")
public class Response implements Serializable {

private static final long serialVersionUID = -8908065160800287163L;
@Label(value = "Route To ADTN")
	private Boolean routeToAdtn;
	@Label(value = "Send To One Click")
	private Boolean sendToOneClick;
	@Label(value = "Send To Email")
	private Boolean sendToEmail;
	@Label(value = "Send To Text")
	private Boolean sendToText;
	@Label(value = "DNIS")
	private Dnis dnis;
	@Label(value = "Web Split")
	private WebSplit webSplit;

	public Response() {
	}

	public Boolean getRouteToAdtn() {
		return this.routeToAdtn;
	}

	public void setRouteToAdtn(Boolean routeToAdtn) {
		this.routeToAdtn = routeToAdtn;
	}

	public Boolean getSendToOneClick() {
		return this.sendToOneClick;
	}

	public void setSendToOneClick(Boolean sendToOneClick) {
		this.sendToOneClick = sendToOneClick;
	}

	public Boolean getSendToEmail() {
		return this.sendToEmail;
	}

	public void setSendToEmail(Boolean sendToEmail) {
		this.sendToEmail = sendToEmail;
	}

	public Boolean getSendToText() {
		return this.sendToText;
	}

	public void setSendToText(Boolean sendToText) {
		this.sendToText = sendToText;
	}

	public Dnis getDnis() {
		return this.dnis;
	}

	public void setDnis(Dnis dnis) {
		this.dnis = dnis;
	}

	public WebSplit getWebSplit() {
		return this.webSplit;
	}

	public void setWebSplit(WebSplit webSplit) {
		this.webSplit = webSplit;
	}

	@Override
	public String toString() {
		return
		"{routeToAdtn: "+routeToAdtn+"\n"+
		" sendToEmail: "+sendToEmail+"\n"+
		" sendToOneClick: "+sendToOneClick+"\n"+
		" sendToText: "+sendToText+"\n"+
		" dnis: \n"+dnis+
		" webSplit: \n"+webSplit+
		"}\n";
	}

	public Response(Boolean routeToAdtn,
			Boolean sendToOneClick, Boolean sendToEmail,
			Boolean sendToText, Dnis dnis,
			WebSplit webSplit) {
		this.routeToAdtn = routeToAdtn;
		this.sendToOneClick = sendToOneClick;
		this.sendToEmail = sendToEmail;
		this.sendToText = sendToText;
		this.dnis = dnis;
		this.webSplit = webSplit;
	}

}