package com.home_security.web_lead;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.kie.api.definition.type.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Label("Web Lead")
public class WebLead implements Serializable {

	private static final long serialVersionUID = 1333220959121141618L;
	@Label("Form Name")
	private String formName;
	@Label("Promotion Code")
	private String promotionCode;
	@Label("Message Division")
	private String messageDivision;
	@Label("Message Type")
	private String messageType;
	@Label("Email Subject")
	private String emailSubject;
	@Label("First Name")
	private String firstName;
	@Label("Last Name")
	private String lastName;
	@Label("State Code")
	private String stateCode;
	@Label("Country Code")
	private String countryCode;
	@Label("ZIP Code")
	private String zipCode;
	@Label("Primary Phone Number")
	private String primaryPhoneNumber;
	@Label("Email Address")
	private String emailAddress;
	@Label("Source IP")
	private String sourceIP;
	@Label("Create Date Time")
	private String createDateTime;

	public WebLead() {
	}

	public String getFormName() {
		return this.formName;
	}

	public void setFormName(String formName) {
		this.formName = formName;
	}

	public String getPromotionCode() {
		return this.promotionCode;
	}

	public void setPromotionCode(String promotionCode) {
		this.promotionCode = promotionCode;
	}

	public String getMessageDivision() {
		return this.messageDivision;
	}

	public void setMessageDivision(String messageDivision) {
		this.messageDivision = messageDivision;
	}

	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public String getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getPrimaryPhoneNumber() {
		return this.primaryPhoneNumber;
	}

	public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
		this.primaryPhoneNumber = primaryPhoneNumber;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getSourceIP() {
		return this.sourceIP;
	}

	public void setSourceIP(String sourceIP) {
		this.sourceIP = sourceIP;
	}

	public String getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(String createDateTime) {
		this.createDateTime = createDateTime;
	}

	@Override
	public String toString() {
		return
		"{countryCode: "+countryCode+"\n"+
		" emailAddress: "+emailAddress+"\n"+
		" firstName: "+firstName+"\n"+
		" formName: "+formName+"\n"+
		" lastName: "+lastName+"\n"+
		" messageDivision: "+messageDivision+"\n"+
		" messageType: "+messageType+"\n"+
		" primaryPhoneNumber: "+primaryPhoneNumber+"\n"+
		" promotionCode: "+promotionCode+"\n"+
		" sourceIP: "+sourceIP+"\n"+
		" stateCode: "+stateCode+"\n"+
		" zipCode: "+zipCode+"\n"+
 		"}\n";
	}

	public WebLead(String formName, String promotionCode,
			String messageDivision, String messageType,
			String emailSubject, String firstName,
			String lastName, String stateCode,
			String countryCode, String zipCode,
			String primaryPhoneNumber, String emailAddress,
			String sourceIP, String createDateTime) {
		this.formName = formName;
		this.promotionCode = promotionCode;
		this.messageDivision = messageDivision;
		this.messageType = messageType;
		this.emailSubject = emailSubject;
		this.firstName = firstName;
		this.lastName = lastName;
		this.stateCode = stateCode;
		this.countryCode = countryCode;
		this.zipCode = zipCode;
		this.primaryPhoneNumber = primaryPhoneNumber;
		this.emailAddress = emailAddress;
		this.sourceIP = sourceIP;
		this.createDateTime = createDateTime;
	}

}