package com.home_security.web_lead;

import java.io.Serializable;

import org.kie.api.definition.type.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Label("Web Split")
public class WebSplit implements Serializable {

	private static final long serialVersionUID = -2629032427412748001L;
	@Label("Matched Name")
	private String matchedName;
	@Label("Split Ratio")
	private String splitRatio;
	@Label("Live Ratio")
	private String liveRatio;

	public WebSplit() {
	}

	public String getMatchedName() {
		return this.matchedName;
	}

	public void setMatchedName(String matchedName) {
		this.matchedName = matchedName;
	}

	public String getSplitRatio() {
		return this.splitRatio;
	}

	public void setSplitRatio(String splitRatio) {
		this.splitRatio = splitRatio;
	}

	public String getLiveRatio() {
		return this.liveRatio;
	}

	public void setLiveRatio(String liveRatio) {
		this.liveRatio = liveRatio;
	}

	@Override
	public String toString() {
		return
		"{matchedName: "+matchedName+"\n"+
		" liveRatio: "+liveRatio+"\n"+
		" splitRatio: "+splitRatio+"\n"+
		"}\n";
	}

	public WebSplit(String matchedName, String splitRatio,
			String liveRatio) {
		this.matchedName = matchedName;
		this.splitRatio = splitRatio;
		this.liveRatio = liveRatio;
	}

}